$ErrorActionPreference = 'Stop'
$Root = Resolve-Path (Join-Path $PSScriptRoot '..')
Set-Location $Root
$EnvFile = Join-Path $Root '.env'
$ExampleFile = Join-Path $Root '.env.example'
$OutFile = Join-Path $Root '.compose.ports.yml'
if (-not (Test-Path -LiteralPath $EnvFile)) {
  Copy-Item -LiteralPath $ExampleFile -Destination $EnvFile -Force
}

function Get-DotEnvValue([string]$Key, [string]$Default) {
  $line = Get-Content -LiteralPath $EnvFile -Encoding UTF8 | Where-Object { $_ -match "^$([regex]::Escape($Key))=" } | Select-Object -Last 1
  if ($line) { return ($line -replace "^$([regex]::Escape($Key))=", '') }
  return $Default
}
function Test-Enabled([string]$Key) {
  $v = (Get-DotEnvValue $Key '0').Trim().ToLowerInvariant()
  return @('1','true','yes','on','enable','enabled') -contains $v
}

$ports = New-Object System.Collections.Generic.List[string]
if (Test-Enabled 'MIRASIM_PUBLISH_WEB') {
  $ports.Add("      - `"$(Get-DotEnvValue 'MIRASIM_WEB_HOST' '0.0.0.0'):$(Get-DotEnvValue 'MIRASIM_WEB_HOST_PORT' '4939'):4939`"")
}
if (Test-Enabled 'MIRASIM_PUBLISH_UNIFIED') {
  $ports.Add("      - `"$(Get-DotEnvValue 'MIRASIM_UNIFIED_HOST' '127.0.0.1'):$(Get-DotEnvValue 'MIRASIM_UNIFIED_HOST_PORT' '12015'):12015`"")
}
if (Test-Enabled 'MIRASIM_PUBLISH_CODEX') {
  $ports.Add("      - `"$(Get-DotEnvValue 'MIRASIM_CODEX_HOST' '127.0.0.1'):$(Get-DotEnvValue 'MIRASIM_CODEX_HOST_PORT' '12017'):12017`"")
}
if (Test-Enabled 'MIRASIM_PUBLISH_CLAUDE') {
  $ports.Add("      - `"$(Get-DotEnvValue 'MIRASIM_CLAUDE_HOST' '127.0.0.1'):$(Get-DotEnvValue 'MIRASIM_CLAUDE_HOST_PORT' '12018'):12018`"")
}

if ($ports.Count -eq 0) {
  $content = "# Auto-generated by scripts/render-ports.ps1. Edit .env instead.`nservices:`n  mirasim: {}`n"
} else {
  $content = "# Auto-generated by scripts/render-ports.ps1. Edit .env instead.`nservices:`n  mirasim:`n    ports:`n" + (($ports | ForEach-Object { "$_`n" }) -join '')
}
[System.IO.File]::WriteAllText($OutFile, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "generated .compose.ports.yml ($($ports.Count) published port(s))"
