#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
ENV_FILE=${ENV_FILE:-.env}
OUT_FILE=${MIRASIM_PORTS_COMPOSE_FILE:-.compose.ports.yml}

if [ ! -f "$ENV_FILE" ]; then
  cp .env.example "$ENV_FILE"
fi

get_env() {
  key="$1"
  value=$(sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n1 || true)
  printf '%s' "$value"
}

enabled() {
  v=$(get_env "$1" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')
  case "$v" in
    1|true|yes|on|enable|enabled) return 0 ;;
    *) return 1 ;;
  esac
}

append_port() {
  host="$1"; host_port="$2"; container_port="$3"
  printf '      - "%s:%s:%s"
' "$host" "$host_port" "$container_port" >> "$OUT_FILE"
}

cat > "$OUT_FILE" <<'YAML'
# Auto-generated by scripts/render-ports.sh. Edit .env instead.
services:
  mirasim:
    ports:
YAML

count=0
if enabled MIRASIM_PUBLISH_WEB; then
  append_port "${MIRASIM_WEB_HOST:-$(get_env MIRASIM_WEB_HOST)}" "${MIRASIM_WEB_HOST_PORT:-$(get_env MIRASIM_WEB_HOST_PORT)}" 4939
  count=$((count+1))
fi
if enabled MIRASIM_PUBLISH_UNIFIED; then
  append_port "${MIRASIM_UNIFIED_HOST:-$(get_env MIRASIM_UNIFIED_HOST)}" "${MIRASIM_UNIFIED_HOST_PORT:-$(get_env MIRASIM_UNIFIED_HOST_PORT)}" 12015
  count=$((count+1))
fi
if enabled MIRASIM_PUBLISH_CODEX; then
  append_port "${MIRASIM_CODEX_HOST:-$(get_env MIRASIM_CODEX_HOST)}" "${MIRASIM_CODEX_HOST_PORT:-$(get_env MIRASIM_CODEX_HOST_PORT)}" 12017
  count=$((count+1))
fi
if enabled MIRASIM_PUBLISH_CLAUDE; then
  append_port "${MIRASIM_CLAUDE_HOST:-$(get_env MIRASIM_CLAUDE_HOST)}" "${MIRASIM_CLAUDE_HOST_PORT:-$(get_env MIRASIM_CLAUDE_HOST_PORT)}" 12018
  count=$((count+1))
fi

if [ "$count" -eq 0 ]; then
  cat > "$OUT_FILE" <<'YAML'
# Auto-generated by scripts/render-ports.sh. Edit .env instead.
services:
  mirasim: {}
YAML
fi

echo "generated $OUT_FILE ($count published port(s))"
